#############################################################################
# Makefile for building: ../build/debug/huffman
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  huffman.pro
# Template: app
# Command: /local/qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile huffman.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I/local/qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I../build/debug/.moc -I/local/qt/5.4/clang_64/mkspecs/macx-clang -F/local/qt/5.4/clang_64/lib
QMAKE         = /local/qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = huffman1.0.0
DISTDIR = /Users/daniel/GitHub/huffman/build/debug/.obj/huffman1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/local/qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/local/qt/5.4/clang_64/lib -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ../build/debug/.obj/

####### Files

SOURCES       = FrequencyTable.cpp \
		Huffman.cpp \
		HuffmanCode.cpp \
		HuffmanNode.cpp \
		HuffmanTest.cpp \
		MemBuffer.cpp \
		Stream.cpp \
		SymbolEncode.cpp \
		Util.cpp \
		main.cpp 
OBJECTS       = ../build/debug/.obj/FrequencyTable.o \
		../build/debug/.obj/Huffman.o \
		../build/debug/.obj/HuffmanCode.o \
		../build/debug/.obj/HuffmanNode.o \
		../build/debug/.obj/HuffmanTest.o \
		../build/debug/.obj/MemBuffer.o \
		../build/debug/.obj/Stream.o \
		../build/debug/.obj/SymbolEncode.o \
		../build/debug/.obj/Util.o \
		../build/debug/.obj/main.o
DIST          = /local/qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/local/qt/5.4/clang_64/mkspecs/qdevice.pri \
		/local/qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/local/qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/local/qt/5.4/clang_64/mkspecs/common/unix.conf \
		/local/qt/5.4/clang_64/mkspecs/common/mac.conf \
		/local/qt/5.4/clang_64/mkspecs/common/macx.conf \
		/local/qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/local/qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/local/qt/5.4/clang_64/mkspecs/common/clang.conf \
		/local/qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/local/qt/5.4/clang_64/mkspecs/qconfig.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/local/qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/local/qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/local/qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/local/qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/local/qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/local/qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/local/qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/local/qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/local/qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/local/qt/5.4/clang_64/mkspecs/features/qt.prf \
		/local/qt/5.4/clang_64/mkspecs/features/resources.prf \
		/local/qt/5.4/clang_64/mkspecs/features/moc.prf \
		/local/qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/local/qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/local/qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/local/qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/local/qt/5.4/clang_64/mkspecs/features/lex.prf \
		huffman.pro FrequencyTable.h \
		Huffman.h \
		HuffmanCode.h \
		HuffmanNode.h \
		MemBuffer.h \
		Stream.h \
		Symbol.h \
		SymbolEncode.h \
		Util.h FrequencyTable.cpp \
		Huffman.cpp \
		HuffmanCode.cpp \
		HuffmanNode.cpp \
		HuffmanTest.cpp \
		MemBuffer.cpp \
		Stream.cpp \
		SymbolEncode.cpp \
		Util.cpp \
		main.cpp
QMAKE_TARGET  = huffman
DESTDIR       = ../build/debug/#avoid trailing-slash linebreak
TARGET        = ../build/debug/huffman

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d ../build/debug/ || mkdir -p ../build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: huffman.pro /local/qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf /local/qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/local/qt/5.4/clang_64/mkspecs/qdevice.pri \
		/local/qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/local/qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/local/qt/5.4/clang_64/mkspecs/common/unix.conf \
		/local/qt/5.4/clang_64/mkspecs/common/mac.conf \
		/local/qt/5.4/clang_64/mkspecs/common/macx.conf \
		/local/qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/local/qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/local/qt/5.4/clang_64/mkspecs/common/clang.conf \
		/local/qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/local/qt/5.4/clang_64/mkspecs/qconfig.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/local/qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/local/qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/local/qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/local/qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/local/qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/local/qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/local/qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/local/qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/local/qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/local/qt/5.4/clang_64/mkspecs/features/qt.prf \
		/local/qt/5.4/clang_64/mkspecs/features/resources.prf \
		/local/qt/5.4/clang_64/mkspecs/features/moc.prf \
		/local/qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/local/qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/local/qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/local/qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/local/qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/local/qt/5.4/clang_64/mkspecs/features/lex.prf \
		huffman.pro \
		/local/qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile huffman.pro
/local/qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
/local/qt/5.4/clang_64/mkspecs/qdevice.pri:
/local/qt/5.4/clang_64/mkspecs/features/device_config.prf:
/local/qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
/local/qt/5.4/clang_64/mkspecs/common/unix.conf:
/local/qt/5.4/clang_64/mkspecs/common/mac.conf:
/local/qt/5.4/clang_64/mkspecs/common/macx.conf:
/local/qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
/local/qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/local/qt/5.4/clang_64/mkspecs/common/clang.conf:
/local/qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
/local/qt/5.4/clang_64/mkspecs/qconfig.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/local/qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/local/qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
/local/qt/5.4/clang_64/mkspecs/features/qt_config.prf:
/local/qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
/local/qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/local/qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
/local/qt/5.4/clang_64/mkspecs/features/default_pre.prf:
/local/qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
/local/qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
/local/qt/5.4/clang_64/mkspecs/features/default_post.prf:
/local/qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
/local/qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
/local/qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
/local/qt/5.4/clang_64/mkspecs/features/warn_on.prf:
/local/qt/5.4/clang_64/mkspecs/features/qt.prf:
/local/qt/5.4/clang_64/mkspecs/features/resources.prf:
/local/qt/5.4/clang_64/mkspecs/features/moc.prf:
/local/qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
/local/qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
/local/qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
/local/qt/5.4/clang_64/mkspecs/features/exceptions.prf:
/local/qt/5.4/clang_64/mkspecs/features/yacc.prf:
/local/qt/5.4/clang_64/mkspecs/features/lex.prf:
huffman.pro:
/local/qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile huffman.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents FrequencyTable.h Huffman.h HuffmanCode.h HuffmanNode.h MemBuffer.h Stream.h Symbol.h SymbolEncode.h Util.h $(DISTDIR)/
	$(COPY_FILE) --parents FrequencyTable.cpp Huffman.cpp HuffmanCode.cpp HuffmanNode.cpp HuffmanTest.cpp MemBuffer.cpp Stream.cpp SymbolEncode.cpp Util.cpp main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

../build/debug/.obj/FrequencyTable.o: FrequencyTable.cpp HuffmanNode.h \
		Stream.h \
		Symbol.h \
		Util.h \
		FrequencyTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/FrequencyTable.o FrequencyTable.cpp

../build/debug/.obj/Huffman.o: Huffman.cpp Util.h \
		Stream.h \
		Symbol.h \
		HuffmanNode.h \
		HuffmanCode.h \
		FrequencyTable.h \
		SymbolEncode.h \
		Huffman.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/Huffman.o Huffman.cpp

../build/debug/.obj/HuffmanCode.o: HuffmanCode.cpp Util.h \
		Stream.h \
		Symbol.h \
		HuffmanCode.h \
		HuffmanNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/HuffmanCode.o HuffmanCode.cpp

../build/debug/.obj/HuffmanNode.o: HuffmanNode.cpp Util.h \
		Stream.h \
		Symbol.h \
		HuffmanNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/HuffmanNode.o HuffmanNode.cpp

../build/debug/.obj/HuffmanTest.o: HuffmanTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/HuffmanTest.o HuffmanTest.cpp

../build/debug/.obj/MemBuffer.o: MemBuffer.cpp Symbol.h \
		MemBuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/MemBuffer.o MemBuffer.cpp

../build/debug/.obj/Stream.o: Stream.cpp MemBuffer.h \
		Symbol.h \
		Stream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/Stream.o Stream.cpp

../build/debug/.obj/SymbolEncode.o: SymbolEncode.cpp HuffmanCode.h \
		HuffmanNode.h \
		Stream.h \
		Symbol.h \
		Util.h \
		SymbolEncode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/SymbolEncode.o SymbolEncode.cpp

../build/debug/.obj/Util.o: Util.cpp Util.h \
		Stream.h \
		Symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/Util.o Util.cpp

../build/debug/.obj/main.o: main.cpp MemBuffer.h \
		Symbol.h \
		Huffman.h \
		Stream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/debug/.obj/main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

